FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build
WORKDIR /src

COPY ["VisitorService.Domain/VisitorService.Domain.csproj", "VisitorService.Domain/"]
COPY ["VisitorService.Infrastructure/VisitorService.Infrastructure.csproj", "VisitorService.Infrastructure/"]
COPY ["VisitorService.Application/VisitorService.Application.csproj", "VisitorService.Application/"]
COPY ["VisitorService.Interfaces/VisitorService.Interfaces.csproj", "VisitorService.Interfaces/"]

RUN dotnet restore "VisitorService.Interfaces/VisitorService.Interfaces.csproj"

COPY VisitorService.Domain/ VisitorService.Domain/
COPY VisitorService.Infrastructure/ VisitorService.Infrastructure/
COPY VisitorService.Application/ VisitorService.Application/
COPY VisitorService.Interfaces/ VisitorService.Interfaces/

WORKDIR "/src/VisitorService.Interfaces"
RUN dotnet publish "VisitorService.Interfaces.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "VisitorService.Interfaces.dll"]